# Generated by Django 4.2.2 on 2023-09-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_barbershop'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
