# Generated by Django 4.2.2 on 2023-09-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_barbershop_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbershop',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
