# Generated by Django 4.2.2 on 2023-09-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_barber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberservice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
