# Generated by Django 4.2.2 on 2023-09-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_barberservice_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('barbershop_name', models.CharField(max_length=200)),
                ('barber_name', models.CharField(max_length=200)),
                ('service_name', models.CharField(max_length=200)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('selected_date', models.DateField()),
                ('selected_time', models.TimeField()),
            ],
        ),
    ]
