# Generated by Django 4.2.2 on 2023-10-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='selected_date',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='selected_time',
            field=models.CharField(),
        ),
    ]
