# Generated by Django 4.2.2 on 2023-10-17 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complite',
            new_name='complete',
        ),
    ]
